# Site settings
title: Deividy' blog
email: deividyz@gmail.com
description: "A blog about code and random stuff"
baseurl: ""
url: "http://deividy.com"
twitter_username: deividyz
github_username:  Deividy
facebook_username: deividyz

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
